services:
  - type: web
    name: mailshield-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: ENVIRONMENT
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_KEY2
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_SAFE_BROWSING_API_KEY
        sync: false
