from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime, timezone


class IndicatorType(str, Enum):
    URL = "url"
    DOMAIN = "domain"
    IP = "ip"
    EMAIL = "email"
    ATTACHMENT = "attachment"


class SeverityLevel(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    CLEAN = "clean"


class SignalCategory(str, Enum):
    AUTHENTICATION = "authentication"
    IDENTITY = "identity"
    ROUTING = "routing"
    URL = "url"
    DOMAIN = "domain"
    CONTENT = "content"
    ATTACHMENT = "attachment"
    STRUCTURE = "structure"
    BEHAVIORAL = "behavioral"


class SignalSeverity(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class ThreatClassification(str, Enum):
    BENIGN = "benign"
    SUSPICIOUS = "suspicious"
    PHISHING = "phishing"
    SPEAR_PHISHING = "spear_phishing"
    CREDENTIAL_HARVESTING = "credential_harvesting"
    BUSINESS_EMAIL_COMPROMISE = "business_email_compromise"
    IMPERSONATION = "impersonation"
    MALICIOUS_LINK = "malicious_link"
    MALICIOUS_ATTACHMENT = "malicious_attachment"
    SPAM = "spam"
    UNKNOWN = "unknown"


class TriageStatus(str, Enum):
    UNREVIEWED = "unreviewed"
    REVIEWING = "reviewing"
    ESCALATED = "escalated"
    RESOLVED = "resolved"
    FALSE_POSITIVE = "false_positive"


class SecuritySignal(BaseModel):
    id: str = Field(..., description="Unique deterministic signal ID, e.g. SIG-AUTH-SPF-01")
    type: str = Field(..., description="Machine-readable signal type name")
    category: SignalCategory = Field(..., description="Controlled security domain category")
    severity: SignalSeverity = Field(..., description="Severity rating of the observation")
    score_contribution: int = Field(..., ge=0, description="Risk score points contributed by this signal")
    title: str = Field(..., description="Human-readable title of the signal")
    description: str = Field(..., description="Detailed description explaining the security significance")
    evidence_references: List[str] = Field(default_factory=list, description="Pointers to originating evidence items")
    confidence: float = Field(default=0.9, ge=0.0, le=1.0, description="Confidence in this specific signal detection")


class StructuredReason(BaseModel):
    title: str = Field(..., description="Short finding headline")
    explanation: str = Field(..., description="Contextual explanation of why this finding indicates risk")
    severity: SignalSeverity = Field(..., description="Finding severity")
    signal_id: Optional[str] = Field(None, description="Linked SecuritySignal ID")
    evidence_references: List[str] = Field(default_factory=list, description="Supporting evidence items")
    score_contribution: int = Field(0, description="Risk contribution value")


class AIExplanation(BaseModel):
    summary: str = Field(..., description="Executive threat overview generated by AI reasoning")
    key_findings: List[str] = Field(default_factory=list, description="Key technical highlights derived from evidence")
    evidence_references: List[str] = Field(default_factory=list, description="Explicit evidence cited by AI")
    recommended_next_step: str = Field(..., description="Actionable SOC triage guidance")
    limitations: str = Field(..., description="Explicit statement of AI boundaries and unverified parameters")


class ThreatIndicator(BaseModel):
    indicator_type: IndicatorType = Field(..., description="Type of extracted IOC")
    value: str = Field(..., description="The indicator value (e.g., domain name, URL, IP)")
    context: Optional[str] = Field(None, description="Where and how the indicator appeared")
    is_malicious: bool = Field(False, description="Whether indicator is deemed malicious by heuristics/rules")


class EvidenceItem(BaseModel):
    field_name: str = Field(..., description="Artifact name (e.g. 'From', 'Reply-To', 'Body Text')")
    raw_value: str = Field(..., description="Raw string extracted from email evidence")
    description: str = Field(..., description="Explainable description of forensic observation")
    is_anomalous: bool = Field(False, description="Flag indicating anomaly detected in this evidence piece")


class ThreatAnalysisRequest(BaseModel):
    subject: str = Field(..., description="Email subject line")
    sender: str = Field(..., description="From header value")
    body: str = Field(..., description="Cleaned email body text")
    html_body: Optional[str] = Field(None, description="Raw or parsed HTML body")
    headers: Optional[Any] = Field(default_factory=dict, description="Raw or parsed email headers")
    raw_headers_list: Optional[List[Dict[str, str]]] = Field(default_factory=list, description="Full header list")
    attachments: Optional[List[Dict[str, Any]]] = Field(default_factory=list, description="Attachment metadata")
    gemini_api_key: Optional[str] = Field(None, description="Optional override Gemini API key")
    openai_api_key: Optional[str] = Field(None, description="Optional override OpenAI API key")


class ThreatAnalysisResult(BaseModel):
    threat_score: int = Field(..., ge=0, le=100, description="Calculated deterministic risk score between 0 and 100")
    severity: SeverityLevel = Field(..., description="Mapped severity level: CLEAN, LOW, MEDIUM, HIGH, CRITICAL")
    classification: ThreatClassification = Field(..., description="Evidence-backed threat classification")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Calculated signal confidence score (0.0 to 1.0)")
    summary: str = Field(..., description="Forensic summary of findings")
    reasons: List[str] = Field(default_factory=list, description="Plain text list of explainable detection reasons")
    structured_reasons: List[StructuredReason] = Field(default_factory=list, description="Detailed structured reasons with score links")
    signals: List[SecuritySignal] = Field(default_factory=list, description="Deterministic security signals detected from evidence")
    indicators: List[ThreatIndicator] = Field(default_factory=list, description="Extracted threat indicators (URLs, domains, IPs)")
    evidence: List[EvidenceItem] = Field(default_factory=list, description="Direct evidence extracted from email artifacts")
    ai_explanation: Optional[AIExplanation] = Field(None, description="Structured AI reasoning output")
    triage_status: TriageStatus = Field(default=TriageStatus.UNREVIEWED, description="Investigator workflow triage status")
    source: str = Field("rule_engine", description="Analysis engine source (gemini-2.5-flash, gpt-4o, rule_engine)")
    analyzed_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat(), description="ISO timestamp of analysis")


class InvestigationSummary(BaseModel):
    id: str
    email_id: str
    subject: str
    sender: str
    threat_score: int
    severity: SeverityLevel
    classification: ThreatClassification
    triage_status: TriageStatus = TriageStatus.UNREVIEWED
    signals_count: int = 0
    created_at: str
